name: Running Code Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Get the username and branch name
      id: vars
      run: |
        # Get the repository owner
        echo "USERNAME=$(echo ${{ github.repository }} | cut -d'/' -f1)" >> $GITHUB_ENV
        
        # Get the branch name
        echo "BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

    - name: Run tests
      run: npm run test
    
    - name: Upload coverage reports to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      uses: codecov/codecov-action@v4.0.1
      with:
        token: $CODECOV_TOKEN
        version: 'v0.6.0'
